const homeActionTypes = {
  FETCH_BLOCKS_START: 'FETCH_BLOCKS_START',
  FETCH_BLOCKS_SUCCESS: 'FETCH_BLOCKS_SUCCESS',
  FETCH_BLOCKS_FAILURE: 'FETCH_BLOCKS_FAILURE'
};

export default homeActionTypes;
