const ActivityActionTypes = {
  FETCH_ACTIVITIES_START: 'FETCH_ACTIVITIES_START',
  FETCH_ACTIVITIES_SUCCESS: 'FETCH_ACTIVITIES_SUCCESS',
  FETCH_ACTIVITIES_FAILURE: 'FETCH_ACTIVITIES_FAILURE'
};

export default ActivityActionTypes;
